# Jenkins Sandbox
version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_sandbox
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ${JENKINS_HOME_PATH}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  agent1:
    image: jenkins/ssh-agent:jdk17
    container_name: jenkins_sandbox_agent1
    privileged: true
    user: root
    expose:
      - 22
  agent2:
    image: jenkins/ssh-agent:jdk17
    container_name: jenkins_sandbox_agent2
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}
  samba:
    image: dperson/samba
    ports:
      - "139:139"
      - "445:445"
    command: "-u 'admin;admin' -s 'shared;/data;yes;no;yes;all;none'"
    volumes:
      - ./samba-data:/data
