---
-
  hosts: localhost
  connection: local
  become_user: root
  become_method: sudo
  become: yes
  vars:
    - jenkins_url: "http://localhost:8080"
    - ssh_user : "jenkins"
    - ssh_private_key_path: "/tmp/agent.rsa"
    - jenkins_user: "admin"
    - jenkins_password: "admin"
    - node_name: "new-node"
    - node_name2: "agent2"
    - node_description: "This is a new Jenkins agent node."
    - remote_root_directory: "/home/jenkins"
    - executors: 3
    - labels: "workers"
    - node_mode: "NORMAL" # NORMAL or EXCLUSIVE
    - ssh_host: "agent-hostname"
    - ssh_port: 22
    - credentials_id: "ansible-creds7"
    - credential_description: "test"
  roles:
    # - { role: bring_up }
    # - { role: unlock_jenkins }
    # - { role: conf_agents }
    - { role: conf }
    - { role: conf_agents }
  tasks:
    - name: test
      debug:
        msg: "hello Anna"
