---
# tasks file for bring_up

- name: Run docker-compose up
  ansible.builtin.shell:
    cmd: docker-compose up -d
    # chdir: /path/to/your/docker-compose-directory
  register: compose_up_output

- name: Print docker-compose output
  ansible.builtin.debug:
    var: compose_up_output.stdout
