---
# vars file for conf_agents
private_key_content: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAQEAxuy2PXeBac24Sr7qNEh2oTn+WEsbQ/dyAO+1LGJQFPBCFwAy+SYi
  7HTuCqQUt48O9NzIyoA4ZNW7GU845gNya78DO2ZAc0C4XpStDrQSQVuiZov7otdY1IJ4Ee
  oiiD6/r2MEhWQVfDDMGnr31xzvAJUONvGvnekE2uoSG3LIXGlsbaujUrPxIBN8rBoQFIlj
  owXnISWhF+dLKJ9Dtzhm7RwYkxpFpsZ0DpPKmfO90cIo1+jPQHzwsvnscZ0c3f24uIrHOA
  mFB3F7pv3Fx9C/W4zbBBVgZTymWKRPgKq6j7vmSweLCIKh2pvg6JD+/L72P8yPs8lU4uzU
  T/bej507+QAAA7gmwWFrJsFhawAAAAdzc2gtcnNhAAABAQDG7LY9d4FpzbhKvuo0SHahOf
  5YSxtD93IA77UsYlAU8EIXADL5JiLsdO4KpBS3jw703MjKgDhk1bsZTzjmA3JrvwM7ZkBz
  QLhelK0OtBJBW6Jmi/ui11jUgngR6iKIPr+vYwSFZBV8MMwaevfXHO8AlQ428a+d6QTa6h
  IbcshcaWxtq6NSs/EgE3ysGhAUiWOjBechJaEX50son0O3OGbtHBiTGkWmxnQOk8qZ873R
  wijX6M9AfPCy+exxnRzd/bi4isc4CYUHcXum/cXH0L9bjNsEFWBlPKZYpE+AqrqPu+ZLB4
  sIgqHam+DokP78vvY/zI+zyVTi7NRP9t6PnTv5AAAAAwEAAQAAAQADm8SnMx/vsDx7wqB9
  /U3a7oc3c86qpMuhH7gMy5BsqM+8xL39TgdL0cfa/Tn7pcaILj8diUY8nLHtq3BlSm0Mw6
  TGiDwlZb2nyDumwiEjUAsPStJwPvF3aBHPMAzwpW7AZY6YmtsBleMF8fLFU1rfNapR2IAu
  ive8aYrq4OH95yAfQmnaNdNNEiVOYg0f2P8HwT6Zsvx7yJVGDUeQAhh6IR/G8s09A1RKkb
  DRUE9fyI+nAU3/PZMni+vTCemslF71MkijRLjslkLUCX1EYwxR2Zmk8c4ZSHOS5OZMHGbM
  3TyPpKwJWN/mnpU9p3ChBTBPYadOVFslxJ1sdRl4gl3HAAAAgQD0y6joZbFjcYEujExnHr
  uKTTsgIJBiGj0782CQAtctlYTTys12IDMJuNKBu9aF7xwaUVAqKaTs3llw280RrrtWdCx5
  E8doY6y+kUvX/8pL+3ciw9PXkVGsrjOS3+p4IgxSO0QZ/zqVvRpsK0HhVBNuQtTfUhJXv6
  3Up5MCnhQqiQAAAIEA9WyLJq5/WNHVSCWfS+aT4UdLQReoZjL/f8yER4mmAmmEPpp6Ja5p
  xqoYi2Xgyq7d5yUJtgwNQl12r9NWfZ5sxqFCB6wpSqc7UQk9kORrwFp5YXcI7JOWI5sZE9
  WvY/Ni4L2clagwRdzNCfGcIKltTEHxmkV9vC1R73U4E9tlwicAAACBAM9/MvtXOFM0afsh
  u4JqcVq31Y+eRLyKcxG++Dgow7VAvr1sY1wNoUS5gfJc7LkMAg8LWTG1KBFvTQkW69j11u
  LlKpCgpnC3vf2eSuPXKPrvSsgjsBluHjJ9IL5W4ry7Ig4ViFA1YY8ZckZZweFZR6/4Vg4p
  kV7mialetMIaW4TfAAAAAAEC
  -----END OPENSSH PRIVATE KEY-----

