---
# tasks file for conf

- name: Fetch Jenkins crumb and save to cookies.txt
  ansible.builtin.shell: |
    curl -u "{{ jenkins_user }}:{{ jenkins_password }}" \
    "{{ jenkins_url }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,%22:%22,//crumb)" \
    --cookie-jar cookies.txt
  register: crumb_output

- name: Set CRUMB fact
  ansible.builtin.set_fact:
    CRUMB: "{{ crumb_output.stdout }}"

  register: api_token_output
- name: Generate new Jenkins API token
  ansible.builtin.shell: |
    curl "http://{{ jenkins_user }}:{{ jenkins_password }}@{{ jenkins_url_stripped }}/user/{{ jenkins_user }}/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken" \
    --data "newTokenName=ansibletoken" \
    -b cookies.txt \
    -H "{{ CRUMB }}"
  register: api_token_output

- name: Set API token fact
  ansible.builtin.set_fact:
    api_token: "{{ api_token_output.stdout }}"

- name: Debug the generated token
  ansible.builtin.debug:
    msg: "token: {{  api_token.data.tokenValue }}"

- name: Set token fact
  ansible.builtin.set_fact:
    jenkins_api_token: "{{ api_token.data.tokenValue }}"

